### ISSUE TITLE
Build fails if using GNU LD version > 2.34

### ISSUE THREAD

**Issue by TimCve** [TimCve/OSDev#1]
Versions of GNU LD above 2.34 do not accept executable files as input to a link, at a certain point in the build process an executable file is used as input to a link, making the file non-executable with chmod -x does not solve the issue.

**Comment by TimCve** [comment]
Issue solved by using a custom version of GNU LD, clone https://github.com/z3r0flag/binutils-2_34.git to get a working version of GNU binutils that can be built from source and used to build SystemZero. See updated README.md for details on that.

**Comment by krzysckh** [comment]
you can add a '-r' flag to line 41 in Makefile to compile it on newer versions of gnu ld.

`${LD} -T ld/loader.ld $^ -o $@` -> `${LD} -r -T ld/loader.ld $^ -o $@`

worked with ld 2.36.1
